### PR TITLE
Always return promise in getBattery()

### LINKED ISSUE #16: getBattery() spec doesn't make sense
It's supposed to return a Promise.  In steps 1 and 2 it can "abort these steps" without returning anything...

### PR DESCRIPTION
**Pull request by anssiko**
Fix #16

### CODE REVIEW

**Comment by anssiko** [comment]
@Honry, could you check and update accordingly the tests at https://github.com/w3c/web-platform-tests/tree/master/battery-status as needed?

To be coordinated with test update done in https://github.com/w3c/web-platform-tests/pull/7944 that aligned tests with spec changes in https://github.com/w3c/battery/pull/13.

Thanks!

**Comment by Honry** [comment]
@anssiko, sure, will take a look.

**Comment by Honry** [comment]
@anssiko, I don't think we need to update tests since the `promise_test` already checks if a function does not return a Promise.

The error message will be something like:
_"navigator.getBattery().then/catch is not a function"_

**Comment by anssiko** [comment]
@Honry, thanks for the confirmation. We're good to merge then since we satisfy the _test as you commit_ policy we follow for specifications in CR or above in this group.

**Pull request merged**
